image: Visual Studio 2017
shallow_clone: true

install:
  - curl -fsSL -O http://prdownloads.sourceforge.net/scons/scons-local-2.5.1.zip
  - 7z x scons-local-2.5.1.zip -oscons

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x64
  - python scons/scons.py platform=windows tools=yes target=release_debug verbose=no warnings=no
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat" -arch=x64
  - python scons/scons.py platform=windows tools=yes target=release_debug verbose=no warnings=no

after_build:
  - 7z a bin\godot-windows-x86_64.zip %APPVEYOR_BUILD_FOLDER%\bin\godot.windows.opt.tools.64.exe
  - 7z a bin\godot-windows-x86.zip %APPVEYOR_BUILD_FOLDEr%\bin\godot.windows.opt.tools.32.exe

artifacts:
  - path: bin\godot-windows-x86_64.zip
    name: Godot Engine Editor for Windows 64-bit

  - path: bin\godot-windows-x86.zip
    name: Godot Engine Editor for Windows 32-bit

deploy:
  release: autobuild
  description: 'Autogenerated Godot Engine Editor build'
  provider: GitHub
  auth_token:
    secure: vCMoPcriBlGoCDnJyJJ+81gsLCRUUdLziDo0CImVJEs6auvFxEHCC7oBTXqO8L/E
  artifact: /bin\\*\.zip/
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: appveyor
    appveyor_repo_tag: false
